bpf/Makefile: Fix compilation with KERNEL=netnext
Running make -C bpf KERNEL=netnext currently fails with:

    In file included from bpf_xdp.c:42:
    In file included from /home/paul/cilium3/bpf/lib/nodeport.h:20:
    In file included from /home/paul/cilium3/bpf/lib/encap.h:11:
    /home/paul/cilium3/bpf/lib/wireguard.h:80:12: error: no member named 'mark' in 'struct xdp_md'
            if ((ctx->mark & MARK_MAGIC_WG_ENCRYPTED) == MARK_MAGIC_WG_ENCRYPTED)
                 ~~~  ^
    1 error generated.

That is because ENABLE_WIREGUARD is enabled even for bpf_xdp. Instead of
enabling it in MAX_BASE_OPTIONS, we should enable it only for bpf_host,
bpf_lxc, and bpf_overlay.

Signed-off-by: Paul Chaignon <paul@cilium.io>